name: csharp_staging

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-csharp_staging}
      POSTGRES_USER: ${POSTGRES_USER:-csharp_staging}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    volumes:
      - "postgres_data:/var/lib/postgresql/data"

  redis:
    image: redis:latest

  web:
    image: csharp:staging
    environment:
      ASPNETCORE_ENVIRONMENT: Staging
    depends_on:
      - postgres
      - redis
    volumes:
      - ./src/Hng.Web/appsettings.Staging.json:/app/appsettings.Staging.json

  nginx:
    image: nginx:latest
    ports:
      - "5010:80"
    depends_on:
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  postgres_data:

