name: csharp_production

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-csharp_production}
      POSTGRES_USER: ${POSTGRES_USER:-csharp_production}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    volumes:
      - "postgres_data:/var/lib/postgresql/data"

  redis:
    image: redis:latest

  web:
    image: csharp:production
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    depends_on:
      - postgres
      - redis
    volumes:
      - ./src/Hng.Web/appsettings.Production.json:/app/appsettings.Production.json # This line was changed because production cannot use the staging database

  nginx:
    image: nginx:latest
    ports:
      - "5020:80"
    depends_on:
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  postgres_data:
