name: csharp_production

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-csharp_production}
      POSTGRES_USER: ${POSTGRES_USER:-csharp_production}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    networks:
      - network 

  redis:
    image: redis:latest
    networks:
     - network     

  web:
    image: csharp:production
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    depends_on:
      - postgres
      - redis
    volumes:
      - ./src/Hng.Web/appsettings.Staging.json:/app/appsettings.Production.json
    networks:
      - network

  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "5020:80"
  #   depends_on:
  #     - web
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  postgres_data:

networks:
  network:
    driver: bridge
