name: Validate PR
on:
  pull_request:
    branches: [dev]
    types: [opened, synchronize, reopened, closed]

jobs:
  deploy-pr:
    environment: 
      name: preview
      url: ${{ steps.deploy.outputs.preview-url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - id: deploy
        name: Pull Request Deploy
        uses: hngprojects/pr-deploy@dev
        with:
          server_host: ${{ secrets.HOST }}
          server_username: ${{ secrets.USERNAME }}
          server_password: ${{ secrets.PASSWORD }}
          server_port: ${{ secrets.PORT }}
          comment: true
          context: '.'
          dockerfile: 'Dockerfile'
          exposed_port: '8000'
          host_volume_path: '/var/'
          container_volume_path: '/var/'
          github_token: ${{ secrets.TOKEN }}
      - name: Print Preview Url
        run: |
          echo "Preview Url: ${{ steps.deploy.outputs.preview-url }}" 
