name: Validate PR
on:
  pull_request:
    branches: [dev]
    types: [opened, synchronize, reopened, closed]
  workflow_dispatch:

jobs:
  deploy-pr:
    environment: 
      name: development
      # url: ${{ steps.deploy.outputs.preview-url }}
    runs-on: ubuntu-latest
    env:
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      SSH_HOST: ${{ secrets.HOST }}
      SSH_PORT: ${{ secrets.SSH_PORT }}
      SSH_PASSWORD: ${{ secrets.PASSWORD }}

    steps:
      - name: Checkout to branch
        uses: actions/checkout@v4
      - id: deploy
        name: Pull Request Deploy
        uses: hngprojects/pr-deploy@dev
        with:
          server_host: ${{ env.HOST }}
          server_username: ${{ env.USERNAME }}
          server_password: ${{ env.PASSWORD }}
          server_port: ${{ secrets.SSH_PORT }}
          comment: true
          context: '.'
          dockerfile: 'Dockerfile'
          exposed_port: '8000'
          host_volume_path: '/var/'
          container_volume_path: '/var/'
          github_token: ${{ secrets.TOKEN }}
      - name: Print Preview Url
        run: |
          echo "Preview Url: ${{ steps.deploy.outputs.preview-url }}" 